### ISSUE TITLE
Publish a feed so that people can subscribe to posts

### ISSUE THREAD

**Issue by thsutton** [CompSciCabal/compscicabal.github.io#1]
Please add an RSS or Atom feed so that people can subscribe to posts.

It's a fairly simple [config change](https://help.github.com/articles/atom-rss-feeds-for-github-pages/).

**Comment by sarostru** [comment]
Good call, I followed the instructions you linked and it seems to work, http://compscicabal.github.io/feed

**Comment by thsutton** [comment]
Subscribed. 

Thanks
